/**
 * Catalogue canonique du bestiaire Tower adapté depuis Torri.
 *
 * Ce fichier ne contient que des données sérialisables. La simulation interprète
 * `signature` et `targeting`; le client interprète la forme, la taille et la faction.
 * Les entrées exclues restent documentées ici afin qu'un futur import ne les réactive
 * pas accidentellement.
 */

export type TowerMonsterFaction =
  | 'forest'
  | 'cave'
  | 'desert'
  | 'graveyard'
  | 'mercenary'
  | 'mountain'
  | 'tribe'
  | 'hell'
  | 'machines'
  | 'timelands'
  | 'unique';

export type TowerMonsterRoleShape =
  'circle' | 'triangle' | 'square' | 'pentagon' | 'hexagon' | 'star';

export type TowerMonsterSizeClass = 'very-small' | 'small' | 'medium' | 'large' | 'very-large';

export type TowerMonsterTargeting =
  'player' | 'isolated-player' | 'turret' | 'heart' | 'hybrid' | 'support';

export type TowerMonsterSpawnMode =
  'natural' | 'emergent' | 'summoned' | 'transient' | 'boss' | 'excluded';

export type TowerMonsterIntroductionTier = 'early' | 'mid' | 'late' | 'boss';

export type TowerMonsterCatalogEntry = Readonly<{
  id: string;
  sourceId: string;
  label: string;
  faction: TowerMonsterFaction;
  roleShape: TowerMonsterRoleShape;
  sizeClass: TowerMonsterSizeClass;
  targeting: TowerMonsterTargeting;
  spawnMode: TowerMonsterSpawnMode;
  introduction: TowerMonsterIntroductionTier;
  threatCost: number;
  /** Identifiant stable de la mécanique distinctive interprétée par le moteur. */
  signature: string;
}>;

type MonsterTuple = readonly [
  id: string,
  sourceId: string,
  label: string,
  faction: TowerMonsterFaction,
  roleShape: TowerMonsterRoleShape,
  sizeClass: TowerMonsterSizeClass,
  targeting: TowerMonsterTargeting,
  spawnMode: TowerMonsterSpawnMode,
  introduction: TowerMonsterIntroductionTier,
  threatCost: number,
  signature: string,
];

const CATALOG_ROWS = [
  // Forêt
  [
    'slime',
    'slime',
    'Slime',
    'forest',
    'circle',
    'small',
    'hybrid',
    'natural',
    'early',
    1,
    'slime-merge',
  ],
  [
    'goblin',
    'goblin',
    'Gobelin',
    'forest',
    'circle',
    'small',
    'hybrid',
    'natural',
    'early',
    2,
    'zigzag-combo',
  ],
  [
    'wolf',
    'wolf',
    'Loup',
    'forest',
    'triangle',
    'medium',
    'isolated-player',
    'natural',
    'early',
    3,
    'circle-pounce',
  ],
  [
    'harpy',
    'harpy',
    'Harpie',
    'forest',
    'pentagon',
    'small',
    'isolated-player',
    'natural',
    'mid',
    5,
    'flying-xp-shot',
  ],
  [
    'protector',
    'protector',
    'Protecteur',
    'forest',
    'square',
    'large',
    'support',
    'natural',
    'mid',
    8,
    'ally-shield',
  ],
  [
    'shepherd',
    'shepherd',
    'Berger',
    'forest',
    'hexagon',
    'medium',
    'support',
    'natural',
    'mid',
    6,
    'herd-allies',
  ],
  [
    'grand-wolf',
    'gwolf',
    'Grand loup',
    'forest',
    'triangle',
    'large',
    'isolated-player',
    'natural',
    'late',
    12,
    'summon-pack',
  ],
  [
    'monster-camp',
    'monsterCamp',
    'Camp de monstres',
    'forest',
    'square',
    'large',
    'support',
    'excluded',
    'late',
    0,
    'excluded-stationary',
  ],
  [
    'greedy-slime',
    'slime_avide',
    'Slime avide',
    'forest',
    'circle',
    'large',
    'hybrid',
    'emergent',
    'mid',
    8,
    'growing-merge',
  ],

  // Grottes
  [
    'bat',
    'bat',
    'Chauve-souris',
    'cave',
    'triangle',
    'very-small',
    'player',
    'natural',
    'early',
    1,
    'flying-swarm',
  ],
  [
    'dark-slime',
    'darkSlime',
    'Slime sombre',
    'cave',
    'circle',
    'small',
    'hybrid',
    'natural',
    'early',
    3,
    'resistant-merge',
  ],
  [
    'spider',
    'spider',
    'Araignée',
    'cave',
    'circle',
    'small',
    'player',
    'natural',
    'early',
    2,
    'poison-sting',
  ],
  [
    'coward',
    'coward',
    'Flipette',
    'cave',
    'triangle',
    'small',
    'turret',
    'natural',
    'mid',
    4,
    'avoid-player',
  ],
  [
    'cave-giant',
    'golem',
    'Géant',
    'cave',
    'square',
    'large',
    'turret',
    'natural',
    'mid',
    8,
    'structure-slam',
  ],
  [
    'bowler',
    'bowler',
    'Bouleur',
    'cave',
    'pentagon',
    'large',
    'support',
    'natural',
    'mid',
    8,
    'throw-ally',
  ],
  [
    'giant-spider',
    'giantSpider',
    'Araignée géante',
    'cave',
    'hexagon',
    'large',
    'hybrid',
    'natural',
    'late',
    13,
    'web-network',
  ],
  [
    'weaver-spider',
    'weaverSpider',
    'Araignée tisseuse',
    'cave',
    'hexagon',
    'small',
    'player',
    'summoned',
    'mid',
    2,
    'web-trail',
  ],
  [
    'spider-queen',
    'spiderQueen',
    'Pondeuse',
    'cave',
    'hexagon',
    'large',
    'support',
    'natural',
    'late',
    14,
    'spider-brood',
  ],

  // Désert
  [
    'sand-slime',
    'sandslime',
    'Slime sableux',
    'desert',
    'circle',
    'small',
    'hybrid',
    'natural',
    'early',
    2,
    'sand-puddle',
  ],
  [
    'mummy',
    'mummy',
    'Momie',
    'desert',
    'square',
    'medium',
    'hybrid',
    'natural',
    'early',
    5,
    'revive-bandages',
  ],
  [
    'mummy-bandages',
    'mummyBandages',
    'Bandelettes',
    'desert',
    'circle',
    'small',
    'support',
    'transient',
    'early',
    0,
    'mummy-downed-state',
  ],
  [
    'hyena',
    'hyena',
    'Hyène',
    'desert',
    'triangle',
    'small',
    'isolated-player',
    'natural',
    'early',
    3,
    'pack-flank',
  ],
  [
    'sand-worm',
    'sandWorm',
    'Ver des sables',
    'desert',
    'triangle',
    'large',
    'hybrid',
    'natural',
    'mid',
    9,
    'burrow-emerge',
  ],
  [
    'scorpion',
    'scorpion',
    'Scorpion',
    'desert',
    'pentagon',
    'small',
    'player',
    'natural',
    'mid',
    4,
    'poison-projectile',
  ],
  [
    'beetle',
    'beetle',
    'Scarabée',
    'desert',
    'square',
    'large',
    'turret',
    'natural',
    'mid',
    9,
    'growing-brood',
  ],
  [
    'mini-beetle',
    'miniBeetle',
    'Petit scarabée',
    'desert',
    'circle',
    'very-small',
    'hybrid',
    'summoned',
    'mid',
    1,
    'latch-bite',
  ],
  [
    'djinn',
    'djinn',
    'Djinn',
    'desert',
    'star',
    'medium',
    'player',
    'natural',
    'late',
    10,
    'blink-cycle',
  ],
  [
    'sand-golem',
    'sandGolem',
    'Golem de sable',
    'desert',
    'square',
    'large',
    'turret',
    'natural',
    'late',
    12,
    'sand-slam',
  ],

  // Cimetière
  [
    'zombie',
    'zombie',
    'Zombie',
    'graveyard',
    'circle',
    'medium',
    'hybrid',
    'natural',
    'early',
    3,
    'out-of-combat-regen',
  ],
  [
    'necromancer',
    'necromancer',
    'Nécromancien',
    'graveyard',
    'hexagon',
    'medium',
    'support',
    'natural',
    'mid',
    11,
    'soul-resurrection',
  ],
  [
    'virus-f',
    'virusF',
    'Virus F',
    'graveyard',
    'hexagon',
    'very-small',
    'support',
    'natural',
    'mid',
    7,
    'ally-camouflage',
  ],
  [
    'stalker',
    'stalker',
    'Harceleur',
    'graveyard',
    'pentagon',
    'medium',
    'isolated-player',
    'natural',
    'mid',
    9,
    'snipe-teleport',
  ],
  [
    'dark-knight',
    'dknight',
    'Chevalier sombre',
    'graveyard',
    'square',
    'large',
    'player',
    'natural',
    'late',
    13,
    'frontal-guard',
  ],
  [
    'skeleton-small',
    'skeleton_small',
    'Squelette (petit)',
    'graveyard',
    'circle',
    'small',
    'hybrid',
    'summoned',
    'early',
    1,
    'bone-strike',
  ],
  [
    'skeleton-medium',
    'skeleton_medium',
    'Squelette (moyen)',
    'graveyard',
    'circle',
    'medium',
    'hybrid',
    'natural',
    'mid',
    5,
    'split-small',
  ],
  [
    'skeleton-large',
    'skeleton_large',
    'Squelette (grand)',
    'graveyard',
    'square',
    'large',
    'hybrid',
    'natural',
    'late',
    13,
    'split-medium',
  ],
  [
    'statue',
    'statue',
    'Statue',
    'graveyard',
    'square',
    'large',
    'player',
    'excluded',
    'mid',
    0,
    'excluded-stationary',
  ],
  [
    'vampire',
    'vampire',
    'Vampire',
    'graveyard',
    'triangle',
    'medium',
    'player',
    'natural',
    'mid',
    8,
    'dash-through',
  ],
  [
    'life-thief',
    'lifeThief',
    'Voleur de vie',
    'graveyard',
    'hexagon',
    'medium',
    'isolated-player',
    'natural',
    'mid',
    8,
    'health-drain',
  ],
  [
    'decomposed-slime',
    'decomposedSlime',
    'Slime décomposé',
    'graveyard',
    'circle',
    'small',
    'hybrid',
    'natural',
    'early',
    4,
    'split-merge',
  ],
  [
    'mini-slime',
    'miniSlime',
    'Mini-slime',
    'graveyard',
    'circle',
    'very-small',
    'hybrid',
    'summoned',
    'early',
    1,
    'tiny-hop',
  ],

  // Mercenaires
  [
    'shooter',
    'shooter',
    'Tireur',
    'mercenary',
    'pentagon',
    'small',
    'player',
    'natural',
    'early',
    4,
    'partner-shot',
  ],
  [
    'thug',
    'thug',
    'Truand',
    'mercenary',
    'circle',
    'large',
    'player',
    'natural',
    'early',
    6,
    'copy-buff',
  ],
  [
    'sniper',
    'sniper',
    'Sniper',
    'mercenary',
    'pentagon',
    'medium',
    'isolated-player',
    'natural',
    'mid',
    8,
    'telegraphed-snipe',
  ],
  [
    'mauga',
    'minigun',
    'Mauga',
    'mercenary',
    'pentagon',
    'large',
    'hybrid',
    'natural',
    'late',
    12,
    'minigun-burst',
  ],
  [
    'looter',
    'looter',
    'Pilleur',
    'mercenary',
    'triangle',
    'medium',
    'turret',
    'natural',
    'mid',
    6,
    'wounded-structure-raid',
  ],
  [
    'super-looter',
    'superLooter',
    'Super Pilleur',
    'mercenary',
    'hexagon',
    'medium',
    'turret',
    'natural',
    'late',
    11,
    'turret-disable',
  ],
  [
    'chief',
    'chief',
    'Chef',
    'mercenary',
    'star',
    'large',
    'hybrid',
    'natural',
    'late',
    13,
    'battle-orders',
  ],
  [
    'grenadier',
    'grenadier',
    'Grenadier',
    'mercenary',
    'pentagon',
    'medium',
    'player',
    'natural',
    'mid',
    8,
    'grenade-barrage',
  ],

  // Montagne
  [
    'frosty',
    'frosty',
    'Glacié',
    'mountain',
    'pentagon',
    'small',
    'player',
    'natural',
    'early',
    4,
    'slow-projectile',
  ],
  [
    'grumpy-dwarf',
    'grumpyDwarf',
    'Nainsatisfait',
    'mountain',
    'hexagon',
    'small',
    'support',
    'natural',
    'mid',
    6,
    'repair-heavy',
  ],
  [
    'cannoneer',
    'cannoneer',
    'Cannonier',
    'mountain',
    'pentagon',
    'large',
    'hybrid',
    'natural',
    'mid',
    10,
    'mobile-cannon',
  ],
  [
    'cannon',
    'cannon',
    'Canon',
    'mountain',
    'pentagon',
    'small',
    'hybrid',
    'excluded',
    'mid',
    0,
    'excluded-stationary',
  ],
  [
    'yeti',
    'yeti',
    'Yéti',
    'mountain',
    'square',
    'large',
    'hybrid',
    'natural',
    'mid',
    11,
    'slow-resist-aura',
  ],
  [
    'blizzard-spirit',
    'blizzardSpirit',
    'Esprit du blizzard',
    'mountain',
    'hexagon',
    'small',
    'player',
    'natural',
    'mid',
    6,
    'freeze-death-zone',
  ],
  [
    'polar-bear',
    'polarBear',
    'Ours polaire',
    'mountain',
    'square',
    'very-large',
    'turret',
    'natural',
    'late',
    14,
    'carry-units',
  ],

  // Tribu
  [
    'summoner',
    'summoner',
    'Invocateur',
    'tribe',
    'hexagon',
    'medium',
    'support',
    'natural',
    'early',
    8,
    'portal-summon',
  ],
  [
    'healer',
    'healer',
    'Soigneur',
    'tribe',
    'hexagon',
    'medium',
    'support',
    'natural',
    'mid',
    8,
    'area-heal',
  ],
  [
    'banner',
    'banner',
    'Porte-étendard',
    'tribe',
    'hexagon',
    'medium',
    'support',
    'natural',
    'mid',
    8,
    'ally-buff',
  ],
  [
    'paramedic',
    'paramedic',
    'Urgentiste',
    'tribe',
    'hexagon',
    'small',
    'support',
    'natural',
    'mid',
    7,
    'emergency-heal',
  ],
  [
    'chanter',
    'chanter',
    'Chanteur',
    'tribe',
    'hexagon',
    'medium',
    'support',
    'natural',
    'late',
    8,
    'battle-cry',
  ],

  // Enfer
  [
    'kamikaze',
    'kamikaze',
    'Kamikaze',
    'hell',
    'triangle',
    'small',
    'turret',
    'natural',
    'early',
    4,
    'turret-explosion',
  ],
  [
    'demon',
    'demon',
    'Démon',
    'hell',
    'circle',
    'medium',
    'player',
    'natural',
    'early',
    4,
    'short-curse',
  ],
  [
    'infernal-tank',
    'tank',
    'Tank',
    'hell',
    'square',
    'very-large',
    'turret',
    'natural',
    'mid',
    12,
    'structure-ram',
  ],
  [
    'kidnapper',
    'kidnapper',
    'Kidnappeur',
    'hell',
    'triangle',
    'medium',
    'isolated-player',
    'natural',
    'mid',
    9,
    'kidnap-drag',
  ],
  [
    'enchainer',
    'enchainer',
    'Enchaîneur',
    'hell',
    'pentagon',
    'medium',
    'player',
    'natural',
    'mid',
    8,
    'chain-radius',
  ],
  [
    'burning-soul',
    'burningSoul',
    'Âme brûlante',
    'hell',
    'star',
    'very-small',
    'player',
    'emergent',
    'mid',
    3,
    'volatile-lifetime',
  ],
  [
    'explosive-slime',
    'explosiveSlime',
    'Slime explosif',
    'hell',
    'circle',
    'small',
    'hybrid',
    'natural',
    'early',
    4,
    'explosive-merge',
  ],
  [
    'infernal-angel',
    'infernalAngel',
    'Ange infernal',
    'hell',
    'star',
    'large',
    'hybrid',
    'natural',
    'late',
    14,
    'revive-burning-aura',
  ],

  // Machines
  [
    'explosive-robot',
    'anti_player',
    'Robot explosif',
    'machines',
    'triangle',
    'small',
    'player',
    'natural',
    'late',
    7,
    'player-explosion',
  ],
  [
    'scrap-reaver',
    'scrapReaver',
    'Défourailleur',
    'machines',
    'square',
    'medium',
    'hybrid',
    'natural',
    'mid',
    8,
    'combat-battery',
  ],
  [
    'drillbot',
    'drillbot',
    'Foreuse',
    'machines',
    'triangle',
    'medium',
    'turret',
    'natural',
    'mid',
    10,
    'burrow-turret',
  ],
  [
    'mortar',
    'mortar',
    'Mortier',
    'machines',
    'pentagon',
    'large',
    'player',
    'excluded',
    'late',
    0,
    'excluded-stationary',
  ],
  [
    'siege-engine',
    'siege',
    'Engin de siège',
    'machines',
    'square',
    'very-large',
    'turret',
    'natural',
    'late',
    15,
    'cargo-assault',
  ],
  [
    'squad-launcher',
    'squadLauncher',
    'Lance-troupe',
    'machines',
    'pentagon',
    'large',
    'turret',
    'natural',
    'mid',
    10,
    'lob-squad',
  ],
  [
    'squadling',
    'squadling',
    'Recrue',
    'machines',
    'square',
    'very-small',
    'turret',
    'summoned',
    'mid',
    1,
    'landing-rush',
  ],

  // Terres du Temps
  [
    'time-warden',
    'timeWarden',
    'Manieur du Temps',
    'timelands',
    'star',
    'very-large',
    'turret',
    'natural',
    'late',
    18,
    'temporal-control',
  ],
  [
    'time-deer',
    'timeDeer',
    'Cerf du Temps',
    'timelands',
    'star',
    'large',
    'support',
    'excluded',
    'late',
    0,
    'excluded-passive',
  ],
  [
    'time-controller',
    'timeController',
    'Contrôleur',
    'timelands',
    'star',
    'large',
    'player',
    'natural',
    'late',
    11,
    'freeze-position-rollback',
  ],
  [
    'time-watch',
    'timeWatch',
    'La Montre',
    'timelands',
    'circle',
    'large',
    'hybrid',
    'natural',
    'late',
    9,
    'time-effect-death',
  ],

  // Unique
  [
    'ancient-guardian',
    'ancientGuardian',
    'Gardien Ancien',
    'unique',
    'star',
    'very-large',
    'hybrid',
    'boss',
    'boss',
    40,
    'guardian-arena-slam',
  ],
] as const satisfies readonly MonsterTuple[];

export const TOWER_MONSTER_CATALOG: readonly TowerMonsterCatalogEntry[] = Object.freeze(
  CATALOG_ROWS.map(
    ([
      id,
      sourceId,
      label,
      faction,
      roleShape,
      sizeClass,
      targeting,
      spawnMode,
      introduction,
      threatCost,
      signature,
    ]) =>
      Object.freeze({
        id,
        sourceId,
        label,
        faction,
        roleShape,
        sizeClass,
        targeting,
        spawnMode,
        introduction,
        threatCost,
        signature,
      }),
  ),
);

export type TowerCatalogMonsterId = (typeof CATALOG_ROWS)[number][0];
export type TowerMonsterSignature = (typeof CATALOG_ROWS)[number][10];

export const TOWER_ACTIVE_MONSTERS = Object.freeze(
  TOWER_MONSTER_CATALOG.filter(
    (monster) => monster.spawnMode !== 'excluded' && monster.spawnMode !== 'transient',
  ),
);

export const TOWER_NATURAL_MONSTERS = Object.freeze(
  TOWER_MONSTER_CATALOG.filter((monster) => monster.spawnMode === 'natural'),
);

export function findTowerMonster(id: string): TowerMonsterCatalogEntry | undefined {
  return TOWER_MONSTER_CATALOG.find((monster) => monster.id === id);
}
